backend:
  name: git-gateway
  branch: main 

media_folder: "static/images"
public_folder: "/images"

site_url: "https://seu-site.netlify.app" # depois atualiza com a URL do Netlify

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/services"   # onde ficam os arquivos de posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Corpo", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Páginas"
    folder: "content/pages"   # onde ficam os arquivos de páginas
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }